apiVersion: v1
kind: Service
metadata:
  name: weather-station
spec:
  ports:
    - port: 8080
      name: http
  clusterIP: None
  selector:
    app: weather-station

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: weather-station
spec:
  serviceName: "weather-station"
  replicas: 10
  selector:
    matchLabels:
      app: weather-station
  template:
    metadata:
      labels:
        app: weather-station
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: weather-station
        image: kmmas/weather-station:1.1
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service:9092"
        - name: HEALTH_CHECK_PORT
          value: "8080"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
